import os
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
group = DefineGroup('Applications',
                    src,
                    CPPPATH=[cwd, os.path.join(cwd, '../../common')],
                    depend=[''])

Return('group')
