from building import *

cwd = GetCurrentDir()

src = Glob('arduino/*.cpp') + Glob('freertos/*.cpp') + Glob('hal/*.cpp')
CPPPATH = [cwd + '/arduino', cwd + '/freertos', cwd + '/hal']

group = DefineGroup('CrossPointPort', src, depend=[''], CPPPATH=CPPPATH)

Return('group')
