// Host-side tests for SdCardFont over a real .cpfont fixture generated by the
// vendored converter (fontconvert_sdcard.py) — proves converter output and
// firmware loader agree on the v4 format, including CJK codepoints, without
// the device. Regenerate the fixture: `uv run tools/build_cjk_font.py --fixture`
// (codepoint set there must stay in sync with the assertions here).

#include <EpdFontFamily.h>
#include <SdCardFont.h>
#include <gtest/gtest.h>

#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

namespace {

// Fixture contents (TestCJK_14.cpfont): ascii + 、。书世你好界， at 14pt,
// styles regular+bold (LXGW WenKai Regular/Medium).
constexpr uint32_t kCpNi = 0x4F60;     // 你
constexpr uint32_t kCpHao = 0x597D;    // 好
constexpr uint32_t kCpShi = 0x4E16;    // 世
constexpr uint32_t kCpJie = 0x754C;    // 界
constexpr uint32_t kCpShu = 0x4E66;    // 书
constexpr uint32_t kCpJuhao = 0x3002;  // 。
constexpr uint32_t kCpDouhao = 0xFF0C; // ，
constexpr uint32_t kCpZhong = 0x4E2D;  // 中 — deliberately NOT in the fixture

std::vector<char> readAll(const char* path) {
  std::ifstream in(path, std::ios::binary);
  EXPECT_TRUE(in.good()) << "cannot read " << path;
  return {std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>()};
}

std::string writeTemp(const char* name, const void* data, size_t len) {
  std::string path = std::string(::testing::TempDir()) + name;
  std::ofstream out(path, std::ios::binary | std::ios::trunc);
  out.write(static_cast<const char*>(data), static_cast<std::streamsize>(len));
  return path;
}

class SdCardFontTest : public ::testing::Test {
 protected:
  void SetUp() override { ASSERT_TRUE(font_.load(FIXTURE_CPFONT)); }
  SdCardFont font_;
};

TEST_F(SdCardFontTest, LoadsV4HeaderAndStyles) {
  EXPECT_EQ(font_.styleCount(), 2);
  EXPECT_TRUE(font_.hasStyle(EpdFontFamily::REGULAR));
  EXPECT_TRUE(font_.hasStyle(EpdFontFamily::BOLD));
  EXPECT_FALSE(font_.hasStyle(EpdFontFamily::ITALIC));
  EXPECT_FALSE(font_.hasStyle(EpdFontFamily::BOLD_ITALIC));
  EXPECT_NE(font_.contentHash(), 0u);
  EXPECT_NE(font_.getEpdFont(EpdFontFamily::REGULAR), nullptr);
  EXPECT_NE(font_.getEpdFont(EpdFontFamily::BOLD), nullptr);
  EXPECT_EQ(font_.getEpdFont(EpdFontFamily::ITALIC), nullptr);
}

TEST_F(SdCardFontTest, MissingStylesFallBack) {
  EXPECT_EQ(font_.resolveStyle(EpdFontFamily::ITALIC), EpdFontFamily::REGULAR);
  EXPECT_EQ(font_.resolveStyle(EpdFontFamily::BOLD_ITALIC), EpdFontFamily::BOLD);
  EXPECT_EQ(font_.resolveStyle(EpdFontFamily::BOLD), EpdFontFamily::BOLD);
}

TEST_F(SdCardFontTest, PrewarmLoadsCjkGlyphs) {
  EXPECT_EQ(font_.prewarm("你好，世界。Hello!"), 0);

  const EpdFont* regular = font_.getEpdFont(EpdFontFamily::REGULAR);
  ASSERT_NE(regular, nullptr);
  for (uint32_t cp : {kCpNi, kCpHao, kCpShi, kCpJie, kCpJuhao, kCpDouhao,
                      static_cast<uint32_t>('H')}) {
    const EpdGlyph* glyph = regular->getGlyph(cp);
    ASSERT_NE(glyph, nullptr) << "missing glyph for U+" << std::hex << cp;
    EXPECT_GT(glyph->advanceX, 0) << "zero advance for U+" << std::hex << cp;
  }

  // CJK ideographs are full-width: noticeably wider than Latin.
  const EpdGlyph* ni = regular->getGlyph(kCpNi);
  const EpdGlyph* latinH = regular->getGlyph('H');
  ASSERT_NE(ni, nullptr);
  ASSERT_NE(latinH, nullptr);
  EXPECT_GT(ni->advanceX, latinH->advanceX);
}

TEST_F(SdCardFontTest, PrewarmBoldStyle) {
  EXPECT_EQ(font_.prewarm("书", 1 << EpdFontFamily::BOLD), 0);
  const EpdFont* bold = font_.getEpdFont(EpdFontFamily::BOLD);
  ASSERT_NE(bold, nullptr);
  const EpdGlyph* glyph = bold->getGlyph(kCpShu);
  ASSERT_NE(glyph, nullptr);
  EXPECT_GT(glyph->advanceX, 0);
}

TEST_F(SdCardFontTest, PrewarmReportsUncoveredCodepoints) {
  // 中 is not in the fixture intervals; misses are counted per prewarmed style.
  EXPECT_EQ(font_.prewarm("中", 1 << EpdFontFamily::REGULAR), 1);
  EXPECT_EQ(font_.prewarm("中中中", 1 << EpdFontFamily::REGULAR), 1)
      << "duplicates count once";
  EXPECT_EQ(font_.prewarm("中"), 2) << "one miss per present style";
}

TEST_F(SdCardFontTest, AdvanceTableCoversCjk) {
  EXPECT_EQ(font_.buildAdvanceTable("你好世界"), 0);
  EXPECT_TRUE(font_.hasAdvanceTable());
  EXPECT_GT(font_.getAdvance(kCpNi, EpdFontFamily::REGULAR), 0);
  EXPECT_GT(font_.getAdvance(kCpJie, EpdFontFamily::REGULAR), 0);
  EXPECT_EQ(font_.getAdvance(kCpZhong, EpdFontFamily::REGULAR), 0);
}

TEST_F(SdCardFontTest, ClearCacheKeepsFontLoadable) {
  EXPECT_EQ(font_.prewarm("你好"), 0);
  font_.clearCache();
  // After clearCache the mini tables are gone; a fresh prewarm must work.
  EXPECT_EQ(font_.prewarm("世界"), 0);
  const EpdFont* regular = font_.getEpdFont(EpdFontFamily::REGULAR);
  ASSERT_NE(regular, nullptr);
  EXPECT_NE(regular->getGlyph(kCpShi), nullptr);
}

TEST(SdCardFontLoadTest, RejectsMissingFile) {
  SdCardFont font;
  EXPECT_FALSE(font.load("/nonexistent/NoSuch_14.cpfont"));
}

TEST(SdCardFontLoadTest, RejectsBadMagic) {
  std::vector<char> bytes = readAll(FIXTURE_CPFONT);
  ASSERT_GE(bytes.size(), 8u);
  bytes[0] = 'X';
  const std::string path = writeTemp("bad_magic.cpfont", bytes.data(), bytes.size());
  SdCardFont font;
  EXPECT_FALSE(font.load(path.c_str()));
}

TEST(SdCardFontLoadTest, RejectsWrongVersion) {
  std::vector<char> bytes = readAll(FIXTURE_CPFONT);
  ASSERT_GE(bytes.size(), 10u);
  bytes[8] = static_cast<char>(0xFF);  // version little-endian @ offset 8
  const std::string path = writeTemp("bad_version.cpfont", bytes.data(), bytes.size());
  SdCardFont font;
  EXPECT_FALSE(font.load(path.c_str()));
}

// Opt-in validation of a real production font (e.g. the LXGWWenKai set from
// `uv run tools/build_cjk_font.py`): CPFONT_EXTRA=/path/to/X.cpfont ctest ...
TEST(SdCardFontLoadTest, LoadsProductionFontWhenProvided) {
  const char* path = getenv("CPFONT_EXTRA");
  if (!path) GTEST_SKIP() << "set CPFONT_EXTRA=/path/to/Font_NN.cpfont";
  SdCardFont font;
  ASSERT_TRUE(font.load(path));
  EXPECT_GE(font.styleCount(), 1);
  // Mixed zh-CN reading sample: ideographs, fullwidth punct, CJK quotes/brackets.
  EXPECT_EQ(font.prewarm("你好，世界。中文测试：“引号”、《书名》……—！？", 1), 0);
  EXPECT_EQ(font.buildAdvanceTable("春江潮水连海平，海上明月共潮生。"), 0);
  EXPECT_GT(font.getAdvance(0x6625, 0), 0);  // 春
}

TEST(SdCardFontLoadTest, RejectsTruncatedFile) {
  std::vector<char> bytes = readAll(FIXTURE_CPFONT);
  ASSERT_GT(bytes.size(), 64u);
  const std::string path = writeTemp("truncated.cpfont", bytes.data(), 64);
  SdCardFont font;
  EXPECT_FALSE(font.load(path.c_str()));
}

}  // namespace
