#!/usr/bin/env python3
# /// script
# requires-python = ">=3.13"
# dependencies = ["pillow"]
# ///
"""Rasterize a monospace TTF into an 8x16 bitmap font C header for hello_wodle.

Output: firmware/hello_wodle/src/font_8x16.h — ASCII 0x20..0x7E, 16 bytes per
glyph (one byte per row, MSB = leftmost pixel).

    uv run tools/gen_font.py
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

GLYPH_W, GLYPH_H = 8, 16
FIRST, LAST = 0x20, 0x7E
CANDIDATES = [
    "/System/Library/Fonts/Menlo.ttc",
    "/System/Library/Fonts/Monaco.ttf",
    "/Library/Fonts/Andale Mono.ttf",
]
OUT = Path(__file__).resolve().parent.parent / "firmware/hello_wodle/src/font_8x16.h"


def pick_font() -> ImageFont.FreeTypeFont:
    for path in CANDIDATES:
        if Path(path).exists():
            # size chosen so glyphs fill ~8x16 cell; Menlo 13px ascent fits
            return ImageFont.truetype(path, 13)
    raise SystemExit(f"no candidate font found: {CANDIDATES}")


def render_glyph(font: ImageFont.FreeTypeFont, ch: str) -> list[int]:
    img = Image.new("L", (GLYPH_W, GLYPH_H), 0)
    draw = ImageDraw.Draw(img)
    draw.text((0, 1), ch, fill=255, font=font)
    rows = []
    px = img.load()
    for y in range(GLYPH_H):
        byte = 0
        for x in range(GLYPH_W):
            if px[x, y] > 96:
                byte |= 0x80 >> x
        rows.append(byte)
    return rows


def main() -> None:
    font = pick_font()
    lines = [
        "/* Generated by tools/gen_font.py — do not edit by hand.",
        f" * 8x16 bitmap font, ASCII 0x{FIRST:02X}..0x{LAST:02X}, MSB = leftmost pixel. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define FONT_W {GLYPH_W}",
        f"#define FONT_H {GLYPH_H}",
        f"#define FONT_FIRST 0x{FIRST:02X}",
        f"#define FONT_LAST 0x{LAST:02X}",
        "",
        f"static const uint8_t font_8x16[{LAST - FIRST + 1}][{GLYPH_H}] = {{",
    ]
    for code in range(FIRST, LAST + 1):
        rows = render_glyph(font, chr(code))
        body = ",".join(f"0x{b:02X}" for b in rows)
        safe = chr(code).replace("\\", "backslash").replace("*/", "* /")
        lines.append(f"    {{{body}}}, /* '{safe}' */")
    lines += ["};", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({LAST - FIRST + 1} glyphs)")


if __name__ == "__main__":
    main()
