#!/usr/bin/env python3
# /// script
# requires-python = ">=3.13"
# dependencies = []
# ///
"""Generate the GBK→Unicode BMP table for vendor/lib/TextEncoding.

Uses Python's builtin 'gbk' codec as ground truth. Layout matches
TextEncoding::gbkToUnicode(): lead 0x81..0xFE (126 rows) × trail 0x40..0xFE
excluding 0x7F (190 cols), row-major; unmapped pairs → U+FFFD.

    uv run tools/gen_gbk_table.py   # rewrites GbkTable.cpp
"""

from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "firmware/crosspoint/vendor/lib/TextEncoding/GbkTable.cpp"

LEADS = range(0x81, 0xFF)  # 126
TRAILS = [t for t in range(0x40, 0xFF) if t != 0x7F]  # 190


def main() -> None:
    rows: list[str] = []
    mapped = 0
    for lead in LEADS:
        vals: list[int] = []
        for trail in TRAILS:
            try:
                ch = bytes((lead, trail)).decode("gbk")
                cp = ord(ch)
                if cp > 0xFFFF:  # GBK is BMP-only; guard anyway
                    cp = 0xFFFD
                else:
                    mapped += 1
            except UnicodeDecodeError:
                cp = 0xFFFD
            vals.append(cp)
        rows.append("    " + ", ".join(f"0x{v:04X}" for v in vals) + f",  // lead 0x{lead:02X}")

    body = "\n".join(rows)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// GENERATED by tools/gen_gbk_table.py — do not edit.\n"
        "// GBK→Unicode BMP, lead 0x81..0xFE × trail 0x40..0xFE (no 0x7F), 0xFFFD = unmapped.\n"
        '#include "GbkTable.h"\n\n'
        f"const uint16_t GBK_TABLE[{len(LEADS) * len(TRAILS)}] = {{\n{body}\n}};\n",
        encoding="utf-8",
    )
    size = len(LEADS) * len(TRAILS) * 2
    print(f"{OUT.name}: {mapped} mapped pairs, table {size} bytes")


if __name__ == "__main__":
    main()
